/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a37ZtVtYSDC6FmRkqCLyA3
// Component: XEFn2jGZQC6Q

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: G0urM0rvD4xu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_meto_deign_system_css from "../meto_deign_system/plasmic.module.css"; // plasmic-import: 2X77A6CrJVTC8zJTD8qsTc/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: a37ZtVtYSDC6FmRkqCLyA3/projectcss
import sty from "./PlasmicMetoMultilineTextInput.module.css"; // plasmic-import: XEFn2jGZQC6Q/css

createPlasmicElementProxy;

export type PlasmicMetoMultilineTextInput__VariantMembers = {
  startIcon: "startIcon";
  endIcon: "endIcon";
};
export type PlasmicMetoMultilineTextInput__VariantsArgs = {
  startIcon?: SingleBooleanChoiceArg<"startIcon">;
  endIcon?: SingleBooleanChoiceArg<"endIcon">;
};
type VariantPropType = keyof PlasmicMetoMultilineTextInput__VariantsArgs;
export const PlasmicMetoMultilineTextInput__VariantProps =
  new Array<VariantPropType>("startIcon", "endIcon");

export type PlasmicMetoMultilineTextInput__ArgsType = {
  value?: string;
  onValueChange?: (val: string) => void;
  placeholder?: string;
  autoSize?: boolean;
  maxline?: number;
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMetoMultilineTextInput__ArgsType;
export const PlasmicMetoMultilineTextInput__ArgProps = new Array<ArgPropType>(
  "value",
  "onValueChange",
  "placeholder",
  "autoSize",
  "maxline",
  "children",
  "slot"
);

export type PlasmicMetoMultilineTextInput__OverridesType = {
  root?: Flex__<"div">;
  textarea?: Flex__<"textarea">;
};

export interface DefaultMetoMultilineTextInputProps {
  value?: string;
  onValueChange?: (val: string) => void;
  placeholder?: string;
  autoSize?: boolean;
  maxline?: number;
  children?: React.ReactNode;
  slot?: React.ReactNode;
  startIcon?: SingleBooleanChoiceArg<"startIcon">;
  endIcon?: SingleBooleanChoiceArg<"endIcon">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMetoMultilineTextInput__RenderFunc(props: {
  variants: PlasmicMetoMultilineTextInput__VariantsArgs;
  args: PlasmicMetoMultilineTextInput__ArgsType;
  overrides: PlasmicMetoMultilineTextInput__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          autoSize: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textarea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.value;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "value",
        type: "writable",
        variableType: "text",

        valueProp: "value",
        onChangeProp: "onValueChange"
      },
      {
        path: "height",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "2.5rem"
      },
      {
        path: "elementId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "startIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.startIcon
      },
      {
        path: "endIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.endIcon
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_meto_deign_system_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root,
        {
          [projectcss.global_theme_light]: hasVariant(
            globalVariants,
            "theme",
            "light"
          ),
          [sty.rootendIcon]: hasVariant($state, "endIcon", "endIcon"),
          [sty.rootstartIcon]: hasVariant($state, "startIcon", "startIcon"),
          [sty.rootstartIcon_endIcon]:
            hasVariant($state, "startIcon", "startIcon") &&
            hasVariant($state, "endIcon", "endIcon")
        }
      )}
    >
      <textarea
        data-plasmic-name={"textarea"}
        data-plasmic-override={overrides.textarea}
        className={classNames(
          projectcss.all,
          projectcss.textarea,
          sty.textarea,
          {
            [sty.textareaendIcon]: hasVariant($state, "endIcon", "endIcon"),
            [sty.textareastartIcon]: hasVariant(
              $state,
              "startIcon",
              "startIcon"
            )
          }
        )}
        id={(() => {
          try {
            return $state.elementId;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        maxLength={(() => {
          try {
            return $props.maxline;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return 5;
            }
            throw e;
          }
        })()}
        onChange={async (...eventArgs: any) => {
          (e => {
            generateStateOnChangeProp($state, ["textarea", "value"])(
              e.target.value
            );
          }).apply(null, eventArgs);

          (async event => {
            const $steps = {};

            $steps["updateValue"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["value"]
                    },
                    operation: 0,
                    value: $state.textarea.value
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateValue"] != null &&
              typeof $steps["updateValue"] === "object" &&
              typeof $steps["updateValue"].then === "function"
            ) {
              $steps["updateValue"] = await $steps["updateValue"];
            }
          }).apply(null, eventArgs);
        }}
        onInput={async event => {
          const $steps = {};

          $steps["runCode"] = $props.autoSize
            ? (() => {
                const actionArgs = {
                  customFunction: async () => {
                    return (() => {
                      $state.height = "2.5rem";
                      return ($state.height =
                        event.currentTarget.scrollHeight + "px");
                    })();
                  }
                };
                return (({ customFunction }) => {
                  return customFunction();
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["runCode"] != null &&
            typeof $steps["runCode"] === "object" &&
            typeof $steps["runCode"].then === "function"
          ) {
            $steps["runCode"] = await $steps["runCode"];
          }
        }}
        placeholder={(() => {
          try {
            return $props.placeholder;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        ref={ref => {
          $refs["textarea"] = ref;
        }}
        style={(() => {
          try {
            return {
              resize: "none",
              overflow: "hidden",
              height: $state.height
            };
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return { resize: "none", overflow: "hidden" };
            }
            throw e;
          }
        })()}
        value={generateStateValueProp($state, ["textarea", "value"]) ?? ""}
      />

      <div
        className={classNames(projectcss.all, sty.freeBox__hwduP, {
          [sty.freeBoxstartIcon__hwduP1Nop7]: hasVariant(
            $state,
            "startIcon",
            "startIcon"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <svg
              className={classNames(projectcss.all, sty.svg__tMyRp)}
              role={"img"}
            />
          ),

          value: args.children
        })}
      </div>
      {(
        hasVariant($state, "endIcon", "endIcon")
          ? true
          : hasVariant($state, "startIcon", "startIcon")
          ? true
          : false
      ) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__e4FFw, {
            [sty.freeBoxendIcon__e4FFWqBacC]: hasVariant(
              $state,
              "endIcon",
              "endIcon"
            ),
            [sty.freeBoxstartIcon__e4FFw1Nop7]: hasVariant(
              $state,
              "startIcon",
              "startIcon"
            ),
            [sty.freeBoxstartIcon_endIcon__e4FFw1Nop7QBacC]:
              hasVariant($state, "startIcon", "startIcon") &&
              hasVariant($state, "endIcon", "endIcon")
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <svg
                className={classNames(projectcss.all, sty.svg__kezVu)}
                role={"img"}
              />
            ),

            value: args.slot
          })}
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "textarea"],
  textarea: ["textarea"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  textarea: "textarea";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMetoMultilineTextInput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMetoMultilineTextInput__VariantsArgs;
    args?: PlasmicMetoMultilineTextInput__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMetoMultilineTextInput__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMetoMultilineTextInput__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMetoMultilineTextInput__ArgProps,
          internalVariantPropNames: PlasmicMetoMultilineTextInput__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMetoMultilineTextInput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMetoMultilineTextInput";
  } else {
    func.displayName = `PlasmicMetoMultilineTextInput.${nodeName}`;
  }
  return func;
}

export const PlasmicMetoMultilineTextInput = Object.assign(
  // Top-level PlasmicMetoMultilineTextInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textarea: makeNodeComponent("textarea"),

    // Metadata about props expected for PlasmicMetoMultilineTextInput
    internalVariantProps: PlasmicMetoMultilineTextInput__VariantProps,
    internalArgProps: PlasmicMetoMultilineTextInput__ArgProps
  }
);

export default PlasmicMetoMultilineTextInput;
/* prettier-ignore-end */
