/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a37ZtVtYSDC6FmRkqCLyA3

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantso0P6Iv2BwtGy } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: o0p6iv2BWTGy/globalVariant
import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: G0urM0rvD4xu/globalVariant
import { useScreenVariants as useScreenVariantsmqI86KQCt1 } from "../meto_deign_system/PlasmicGlobalVariant__Screen"; // plasmic-import: mqI__86kQCt1/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantso0P6Iv2BwtGy,
  theme: useTheme,
  screen: useScreenVariantsmqI86KQCt1
});
