/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a37ZtVtYSDC6FmRkqCLyA3
// Component: eACF_em_NR97

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_meto_deign_system_css from "../meto_deign_system/plasmic.module.css"; // plasmic-import: 2X77A6CrJVTC8zJTD8qsTc/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: a37ZtVtYSDC6FmRkqCLyA3/projectcss
import sty from "./PlasmicUploudeTime.module.css"; // plasmic-import: eACF_em_NR97/css

createPlasmicElementProxy;

export type PlasmicUploudeTime__VariantMembers = {
  textSize: "lg" | "base2" | "small";
  chat: "chat";
};
export type PlasmicUploudeTime__VariantsArgs = {
  textSize?: SingleChoiceArg<"lg" | "base2" | "small">;
  chat?: SingleBooleanChoiceArg<"chat">;
};
type VariantPropType = keyof PlasmicUploudeTime__VariantsArgs;
export const PlasmicUploudeTime__VariantProps = new Array<VariantPropType>(
  "textSize",
  "chat"
);

export type PlasmicUploudeTime__ArgsType = { posttime?: any };
type ArgPropType = keyof PlasmicUploudeTime__ArgsType;
export const PlasmicUploudeTime__ArgProps = new Array<ArgPropType>("posttime");

export type PlasmicUploudeTime__OverridesType = {
  root?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultUploudeTimeProps {
  posttime?: any;
  textSize?: SingleChoiceArg<"lg" | "base2" | "small">;
  chat?: SingleBooleanChoiceArg<"chat">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUploudeTime__RenderFunc(props: {
  variants: PlasmicUploudeTime__VariantsArgs;
  args: PlasmicUploudeTime__ArgsType;
  overrides: PlasmicUploudeTime__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "time",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.posttime;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {};
              }
              throw e;
            }
          })()
      },
      {
        path: "textSize",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.textSize
      },
      {
        path: "chat",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.chat
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_meto_deign_system_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.textchat]: hasVariant($state, "chat", "chat"),
          [sty.texttextSize_base2]: hasVariant($state, "textSize", "base2"),
          [sty.texttextSize_lg]: hasVariant($state, "textSize", "lg"),
          [sty.texttextSize_small]: hasVariant($state, "textSize", "small")
        })}
      >
        {hasVariant($state, "chat", "chat") ? (
          <React.Fragment>
            {(() => {
              try {
                return (() => {
                  function pad(n) {
                    return n.toString().padStart(2, "0");
                  }
                  function toPersianDate(date) {
                    const fa = new Intl.DateTimeFormat("fa-IR", {
                      year: "numeric",
                      month: "2-digit",
                      day: "2-digit"
                    }).format(date);
                    return fa.replaceAll("/", "/");
                  }
                  const now = new Date();
                  let updatedAt = new Date($state.time.replace(" ", "T"));
                  const postTime =
                    `${updatedAt.getFullYear()}-${pad(
                      updatedAt.getMonth() + 1
                    )}-${pad(updatedAt.getDate())}T` +
                    `${pad(updatedAt.getHours())}:${pad(
                      updatedAt.getMinutes()
                    )}:${pad(updatedAt.getSeconds())}+03:30`;
                  const inputDate = new Date(postTime);
                  const diffMs = now - inputDate;
                  const minutes = Math.floor(diffMs / (1000 * 60));
                  const hours = Math.floor(diffMs / (1000 * 3600));
                  const days = Math.floor(diffMs / (1000 * 3600 * 24));
                  const months = Math.floor(days / 30);
                  const years = Math.floor(months / 12);
                  let output = "";
                  if (minutes < 60) {
                    output = `امروز`;
                  } else if (hours < 24) {
                    output = `امروز`;
                  } else if (days < 7) {
                    output = `${days} روز پیش`;
                  } else {
                    output = toPersianDate(inputDate);
                  }
                  return output;
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "\u0632\u0645\u0627\u0646 \u0628\u0627\u0631\u06af\u0632\u0627\u0631\u06cc ";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        ) : (
          <React.Fragment>
            {(() => {
              try {
                return (() => {
                  function pad(n) {
                    return n.toString().padStart(2, "0");
                  }
                  const now = new Date();
                  let updatedAt = new Date($state.time.replace(" ", "T"));
                  const postTime =
                    `${updatedAt.getFullYear()}-${pad(
                      updatedAt.getMonth() + 1
                    )}-${pad(updatedAt.getDate())}T` +
                    `${pad(updatedAt.getHours())}:${pad(
                      updatedAt.getMinutes()
                    )}:${pad(updatedAt.getSeconds())}+03:30`;
                  const inputDate = new Date(postTime);
                  const diffMs = now - inputDate;
                  const minutes = Math.floor(diffMs / (1000 * 60));
                  const hours = Math.floor(diffMs / (1000 * 3600));
                  const days = Math.floor(diffMs / (1000 * 3600 * 24));
                  const months = Math.floor(days / 30);
                  const years = Math.floor(months / 12);
                  let output = "";
                  if (minutes < 60) {
                    output = `${minutes} دقیقه پیش`;
                  } else if (hours < 24) {
                    output = `${hours} ساعت پیش`;
                  } else if (days < 7) {
                    output = `${days} روز پیش`;
                  } else if (days < 30) {
                    output = `${Math.floor(days / 7)} هفته پیش`;
                  } else if (months < 12) {
                    output = `${months} ماه پیش`;
                  } else {
                    const remainingMonths = months % 12;
                    output =
                      remainingMonths === 0
                        ? `${years} سال پیش`
                        : `${years} سال و ${remainingMonths} ماه پیش`;
                  }
                  return output;
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "\u0632\u0645\u0627\u0646 \u0628\u0627\u0631\u06af\u0632\u0627\u0631\u06cc ";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        )}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUploudeTime__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUploudeTime__VariantsArgs;
    args?: PlasmicUploudeTime__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUploudeTime__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUploudeTime__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUploudeTime__ArgProps,
          internalVariantPropNames: PlasmicUploudeTime__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUploudeTime__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUploudeTime";
  } else {
    func.displayName = `PlasmicUploudeTime.${nodeName}`;
  }
  return func;
}

export const PlasmicUploudeTime = Object.assign(
  // Top-level PlasmicUploudeTime renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicUploudeTime
    internalVariantProps: PlasmicUploudeTime__VariantProps,
    internalArgProps: PlasmicUploudeTime__ArgProps
  }
);

export default PlasmicUploudeTime;
/* prettier-ignore-end */
