/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5dGW8Awro3qq8Hh5MveXLP

import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5dGW8Awro3qq8Hh5MveXLP/projectModule

import * as projectcss from "./plasmic.module.css"; // plasmic-import: 5dGW8Awro3qq8Hh5MveXLP/projectcss

const data = {
  base: projectcss.plasmic_tokens,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
