/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2X77A6CrJVTC8zJTD8qsTc
// Component: pN1B_aUf5QUi

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Dialog } from "@plasmicpkgs/radix-ui";
import { DialogContent } from "@plasmicpkgs/radix-ui";
import { DialogTitle } from "@plasmicpkgs/radix-ui";
import { DialogClose } from "@plasmicpkgs/radix-ui";

import { useScreenVariants as useScreenVariantsmqI86KQCt1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: mqI__86kQCt1/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2X77A6CrJVTC8zJTD8qsTc/projectcss
import sty from "./PlasmicMetoModal.module.css"; // plasmic-import: pN1B_aUf5QUi/css

import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: XxR6rXEBGfVK/icon

createPlasmicElementProxy;

export type PlasmicMetoModal__VariantMembers = {
  noTrigger: "noTrigger";
  hideHeader: "hideHeader";
  noSpacing: "noSpacing";
  fullScreen: "fullScreen";
  background: "dark" | "black";
};
export type PlasmicMetoModal__VariantsArgs = {
  noTrigger?: SingleBooleanChoiceArg<"noTrigger">;
  hideHeader?: SingleBooleanChoiceArg<"hideHeader">;
  noSpacing?: SingleBooleanChoiceArg<"noSpacing">;
  fullScreen?: SingleBooleanChoiceArg<"fullScreen">;
  background?: SingleChoiceArg<"dark" | "black">;
};
type VariantPropType = keyof PlasmicMetoModal__VariantsArgs;
export const PlasmicMetoModal__VariantProps = new Array<VariantPropType>(
  "noTrigger",
  "hideHeader",
  "noSpacing",
  "fullScreen",
  "background"
);

export type PlasmicMetoModal__ArgsType = {
  open?: boolean;
  onOpenChange?: (val: boolean) => void;
  title?: React.ReactNode;
  body?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMetoModal__ArgsType;
export const PlasmicMetoModal__ArgProps = new Array<ArgPropType>(
  "open",
  "onOpenChange",
  "title",
  "body"
);

export type PlasmicMetoModal__OverridesType = {
  dialog?: Flex__<typeof Dialog>;
  dialogContent?: Flex__<typeof DialogContent>;
  section?: Flex__<"section">;
  dialogTitle?: Flex__<typeof DialogTitle>;
  h5?: Flex__<"h5">;
  dialogClose?: Flex__<typeof DialogClose>;
  svg?: Flex__<"svg">;
};

export interface DefaultMetoModalProps {
  open?: boolean;
  onOpenChange?: (val: boolean) => void;
  title?: React.ReactNode;
  body?: React.ReactNode;
  noTrigger?: SingleBooleanChoiceArg<"noTrigger">;
  hideHeader?: SingleBooleanChoiceArg<"hideHeader">;
  noSpacing?: SingleBooleanChoiceArg<"noSpacing">;
  fullScreen?: SingleBooleanChoiceArg<"fullScreen">;
  background?: SingleChoiceArg<"dark" | "black">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMetoModal__RenderFunc(props: {
  variants: PlasmicMetoModal__VariantsArgs;
  args: PlasmicMetoModal__ArgsType;
  overrides: PlasmicMetoModal__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dialog.open",
        type: "writable",
        variableType: "boolean",

        valueProp: "open",
        onChangeProp: "onOpenChange"
      },
      {
        path: "noTrigger",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noTrigger
      },
      {
        path: "hideHeader",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.hideHeader
      },
      {
        path: "noSpacing",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noSpacing
      },
      {
        path: "fullScreen",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.fullScreen
      },
      {
        path: "background",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.background
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsmqI86KQCt1()
  });

  return (
    <Dialog
      data-plasmic-name={"dialog"}
      data-plasmic-override={overrides.dialog}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.dialog,
        {
          [sty.dialogbackground_black]: hasVariant(
            $state,
            "background",
            "black"
          ),
          [sty.dialogbackground_dark]: hasVariant($state, "background", "dark"),
          [sty.dialogbackground_dark_fullScreen]:
            hasVariant($state, "background", "dark") &&
            hasVariant($state, "fullScreen", "fullScreen"),
          [sty.dialogfullScreen]: hasVariant(
            $state,
            "fullScreen",
            "fullScreen"
          ),
          [sty.dialoghideHeader]: hasVariant(
            $state,
            "hideHeader",
            "hideHeader"
          ),
          [sty.dialognoSpacing]: hasVariant($state, "noSpacing", "noSpacing"),
          [sty.dialognoTrigger]: hasVariant($state, "noTrigger", "noTrigger")
        }
      )}
      defaultOpen={true}
      onOpenChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["dialog", "open"]).apply(
          null,
          eventArgs
        );
      }}
      open={generateStateValueProp($state, ["dialog", "open"])}
      overlayClassName={classNames({
        [sty["pcls_KzAR8UPeSHan"]]:
          hasVariant($state, "fullScreen", "fullScreen") &&
          hasVariant(globalVariants, "screen", "mobileOnly"),
        [sty["pcls_PVeGXLj-2QI7"]]: hasVariant(
          $state,
          "fullScreen",
          "fullScreen"
        ),
        [sty["pcls_gn9jceeBZCzs"]]: true,
        [sty["pcls_xGI3d3PaP1WV"]]: hasVariant(
          globalVariants,
          "screen",
          "mobileOnly"
        )
      })}
      themeResetClass={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens
      )}
      triggerSlot={null}
    >
      <DialogContent
        data-plasmic-name={"dialogContent"}
        data-plasmic-override={overrides.dialogContent}
        className={classNames("__wab_instance", sty.dialogContent, {
          [sty.dialogContentbackground_black]: hasVariant(
            $state,
            "background",
            "black"
          ),
          [sty.dialogContentbackground_dark]: hasVariant(
            $state,
            "background",
            "dark"
          ),
          [sty.dialogContentbackground_dark_fullScreen]:
            hasVariant($state, "background", "dark") &&
            hasVariant($state, "fullScreen", "fullScreen"),
          [sty.dialogContentfullScreen]: hasVariant(
            $state,
            "fullScreen",
            "fullScreen"
          ),
          [sty.dialogContenthideHeader]: hasVariant(
            $state,
            "hideHeader",
            "hideHeader"
          ),
          [sty.dialogContentnoSpacing]: hasVariant(
            $state,
            "noSpacing",
            "noSpacing"
          )
        })}
        themeResetClass={classNames(
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens
        )}
      >
        <section
          data-plasmic-name={"section"}
          data-plasmic-override={overrides.section}
          className={classNames(projectcss.all, sty.section, {
            [sty.sectionbackground_black]: hasVariant(
              $state,
              "background",
              "black"
            ),
            [sty.sectionbackground_dark]: hasVariant(
              $state,
              "background",
              "dark"
            ),
            [sty.sectionbackground_dark_fullScreen]:
              hasVariant($state, "background", "dark") &&
              hasVariant($state, "fullScreen", "fullScreen"),
            [sty.sectionfullScreen]: hasVariant(
              $state,
              "fullScreen",
              "fullScreen"
            )
          })}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__tfB4A, {
              [sty.freeBoxbackground_dark_fullScreen__tfB4AhYb2RHxtAl]:
                hasVariant($state, "background", "dark") &&
                hasVariant($state, "fullScreen", "fullScreen"),
              [sty.freeBoxhideHeader__tfB4AR9YCt]: hasVariant(
                $state,
                "hideHeader",
                "hideHeader"
              )
            })}
            dir={``}
          >
            <DialogTitle
              data-plasmic-name={"dialogTitle"}
              data-plasmic-override={overrides.dialogTitle}
              className={classNames("__wab_instance", sty.dialogTitle)}
            >
              <h5
                data-plasmic-name={"h5"}
                data-plasmic-override={overrides.h5}
                className={classNames(projectcss.all, projectcss.h5, sty.h5, {
                  [sty.h5background_dark_fullScreen]:
                    hasVariant($state, "background", "dark") &&
                    hasVariant($state, "fullScreen", "fullScreen")
                })}
              >
                {renderPlasmicSlot({
                  defaultContents: "Title",
                  value: args.title,
                  className: classNames(sty.slotTargetTitle)
                })}
              </h5>
            </DialogTitle>
          </Stack__>
          <div
            className={classNames(projectcss.all, sty.freeBox__lxgQv, {
              [sty.freeBoxbackground_dark_fullScreen__lxgQVhYb2RHxtAl]:
                hasVariant($state, "background", "dark") &&
                hasVariant($state, "fullScreen", "fullScreen"),
              [sty.freeBoxhideHeader__lxgQvr9YCt]: hasVariant(
                $state,
                "hideHeader",
                "hideHeader"
              )
            })}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4W8Yq
                  )}
                >
                  {"You can insert body content here in this slot."}
                </div>
              ),
              value: args.body
            })}
          </div>
        </section>
        <DialogClose
          data-plasmic-name={"dialogClose"}
          data-plasmic-override={overrides.dialogClose}
          className={classNames("__wab_instance", sty.dialogClose, {
            [sty.dialogClosebackground_dark_fullScreen]:
              hasVariant($state, "background", "dark") &&
              hasVariant($state, "fullScreen", "fullScreen"),
            [sty.dialogClosehideHeader]: hasVariant(
              $state,
              "hideHeader",
              "hideHeader"
            )
          })}
        >
          <XIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg, {
              [sty.svgbackground_dark_fullScreen]:
                hasVariant($state, "background", "dark") &&
                hasVariant($state, "fullScreen", "fullScreen")
            })}
            role={"img"}
          />
        </DialogClose>
      </DialogContent>
    </Dialog>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dialog: [
    "dialog",
    "dialogContent",
    "section",
    "dialogTitle",
    "h5",
    "dialogClose",
    "svg"
  ],
  dialogContent: [
    "dialogContent",
    "section",
    "dialogTitle",
    "h5",
    "dialogClose",
    "svg"
  ],
  section: ["section", "dialogTitle", "h5"],
  dialogTitle: ["dialogTitle", "h5"],
  h5: ["h5"],
  dialogClose: ["dialogClose", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dialog: typeof Dialog;
  dialogContent: typeof DialogContent;
  section: "section";
  dialogTitle: typeof DialogTitle;
  h5: "h5";
  dialogClose: typeof DialogClose;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMetoModal__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMetoModal__VariantsArgs;
    args?: PlasmicMetoModal__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMetoModal__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMetoModal__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMetoModal__ArgProps,
          internalVariantPropNames: PlasmicMetoModal__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMetoModal__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dialog") {
    func.displayName = "PlasmicMetoModal";
  } else {
    func.displayName = `PlasmicMetoModal.${nodeName}`;
  }
  return func;
}

export const PlasmicMetoModal = Object.assign(
  // Top-level PlasmicMetoModal renders the root element
  makeNodeComponent("dialog"),
  {
    // Helper components rendering sub-elements
    dialogContent: makeNodeComponent("dialogContent"),
    section: makeNodeComponent("section"),
    dialogTitle: makeNodeComponent("dialogTitle"),
    h5: makeNodeComponent("h5"),
    dialogClose: makeNodeComponent("dialogClose"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicMetoModal
    internalVariantProps: PlasmicMetoModal__VariantProps,
    internalArgProps: PlasmicMetoModal__ArgProps
  }
);

export default PlasmicMetoModal;
/* prettier-ignore-end */
